source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs'

platform :ios, '13.0'

target 'UnityFramework' do
  pod 'Firebase/AppCheck', '11.14.0'
  pod 'Firebase/Auth', '11.14.0'
  pod 'Firebase/Core', '11.14.0'
  pod 'Firebase/Crashlytics', '11.14.0'
  pod 'Firebase/Database', '11.14.0'
  pod 'Firebase/Firestore', '11.14.0'
  pod 'Firebase/Functions', '11.14.0'
  pod 'Firebase/Messaging', '11.14.0'
  pod 'Firebase/Storage', '11.14.0'
  pod 'GoogleMobileAdsMediationUnity', '4.12.3.0'
  pod 'Google-Mobile-Ads-SDK', '~> 12.6.0'
  pod 'GoogleUserMessagingPlatform', '3.0.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
